name: Weekly Job

on:
  schedule:
    - cron: '0 18 * * 6'
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  run-code:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    permissions:
      contents: write  # Required for committing thumbnails back to repo
    env:
      THUMBNAIL_DIR: 'thumbnails'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required to access commit history for thumbnails

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ${{ env.THUMBNAIL_DIR }}
          key: ${{ runner.os }}-deps-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-deps-

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1 libtiff-dev

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the code
        env:
          host: ${{ secrets.DB_HOST }}
          user: ${{ secrets.DB_USER }}
          password: ${{ secrets.DB_PASSWORD }}
          database: ${{ secrets.DB_NAME }}
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          python main.py

      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: error-logs-${{ github.run_number }}
          path: |
            *.log
            logs/
          retention-days: 7
          if-no-files-found: ignore

      - name: Notify on failure
        if: failure()
        run: |
          echo "::error::Job failed. Check the logs for details."

      - name: Commit updated thumbnails
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add ${{ env.THUMBNAIL_DIR }}
          git commit -m "Update thumbnails [skip ci]" || echo "No thumbnail changes"
          git push || echo "No changes to push"